version: '3.5'

services:
  db:
    container_name: weatherapp-db
    image: devopseasylearning/weatherapp-db:v1
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - weatherapp
    restart: always

  redis:
    container_name: weatherapp-redis
    image: devopseasylearning/weatherapp-redis:v1
    networks:
      - weatherapp
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    volumes:
      - redis-data:/data
    restart: always

  weather:
    container_name: weatherapp-weather
    image: devopseasylearning/weatherapp-weather:v1
    expose:
      - 5000
    environment:
      APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    networks:
      - weatherapp
    restart: always
    depends_on:
      - db
      - redis

  auth:
    container_name: weatherapp-auth
    image: devopseasylearning/weatherapp-auth:v1
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    expose:
      - 8080
    networks:
      - weatherapp
    restart: always
    depends_on:
      - weather

  ui:
    container_name: weatherapp-ui
    image: devopseasylearning/weatherapp-ui:v1
    environment:
      ERIC: eric  # Corrected environment variable name
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - weatherapp
    restart: always
    depends_on:
      - auth

networks:
  weatherapp:

volumes:
  db-data
  redis-data
